import type {
  User,
  Project,
  PullRequest,
  Deployment,
  Incident,
  DashboardMetrics,
  DeploymentChartDataPoint,
  PerformanceChartDataPoint,
  ActivityFeedItem,
  Commit,
  FileChange,
  Check,
  Comment,
  DeploymentLogEntry,
  DeploymentMetric,
  IncidentTimelineEvent,
} from '@/types';

export const currentUser: User = {
  id: 'user-1',
  name: 'Alex Chen',
  email: 'demo@example.com',
  avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
  role: 'ADMIN',
  status: 'online',
  lastActive: '2026-10-05T10:00:00Z',
};

export const teamMembers: User[] = [
  currentUser,
  {
    id: 'user-2',
    name: 'Sarah Kim',
    email: 'sarah.kim@company.com',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    role: 'MANAGER',
    status: 'online',
    lastActive: '2026-10-05T09:45:00Z',
  },
  {
    id: 'user-3',
    name: 'Marcus Rivera',
    email: 'marcus.rivera@company.com',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus',
    role: 'DEVELOPER',
    status: 'away',
    lastActive: '2026-10-05T08:30:00Z',
  },
  {
    id: 'user-4',
    name: 'Priya Patel',
    email: 'priya.patel@company.com',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
    role: 'DEVELOPER',
    status: 'online',
    lastActive: '2026-10-05T09:58:00Z',
  },
  {
    id: 'user-5',
    name: 'Jordan Lee',
    email: 'jordan.lee@company.com',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jordan',
    role: 'DEVELOPER',
    status: 'offline',
    lastActive: '2026-10-04T18:22:00Z',
  },
  {
    id: 'user-6',
    name: 'Emma Wilson',
    email: 'emma.wilson@company.com',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    role: 'MANAGER',
    status: 'offline',
    lastActive: '2026-10-04T17:00:00Z',
  },
];

const avatar = (name: string) =>
  `https://api.dicebear.com/7.x/avataaars/svg?seed=${encodeURIComponent(name)}`;

export const projects: Project[] = [
  {
    id: 'proj-1',
    name: 'Atlas Web Platform',
    description:
      'Customer-facing web application powering the main product dashboard and analytics suite.',
    repository: 'company/atlas-web',
    branch: 'main',
    status: 'active',
    deploymentStatus: 'success',
    openPRs: 7,
    incidents: 1,
    healthScore: 87,
    lastDeployment: '2026-10-05T08:30:00Z',
    contributors: 12,
    stars: 48,
    language: 'TypeScript',
    tags: ['frontend', 'nextjs', 'critical'],
    createdAt: '2025-06-15T00:00:00Z',
  },
  {
    id: 'proj-2',
    name: 'Orion API Gateway',
    description:
      'High-throughput API gateway handling authentication, rate limiting, and request routing for all services.',
    repository: 'company/orion-gateway',
    branch: 'main',
    status: 'active',
    deploymentStatus: 'failed',
    openPRs: 3,
    incidents: 2,
    healthScore: 64,
    lastDeployment: '2026-10-05T07:15:00Z',
    contributors: 8,
    stars: 31,
    language: 'Go',
    tags: ['backend', 'infrastructure', 'critical'],
    createdAt: '2025-03-20T00:00:00Z',
  },
  {
    id: 'proj-3',
    name: 'Nimbus Design System',
    description:
      'Shared component library and design tokens powering all internal and external applications.',
    repository: 'company/nimbus-ds',
    branch: 'main',
    status: 'active',
    deploymentStatus: 'success',
    openPRs: 2,
    incidents: 0,
    healthScore: 95,
    lastDeployment: '2026-10-04T16:00:00Z',
    contributors: 6,
    stars: 67,
    language: 'TypeScript',
    tags: ['design-system', 'shared'],
    createdAt: '2025-08-01T00:00:00Z',
  },
  {
    id: 'proj-4',
    name: 'Pulse Mobile App',
    description:
      'Cross-platform mobile application for real-time notifications, monitoring, and on-call management.',
    repository: 'company/pulse-mobile',
    branch: 'develop',
    status: 'active',
    deploymentStatus: 'in_progress',
    openPRs: 5,
    incidents: 0,
    healthScore: 78,
    lastDeployment: '2026-10-05T09:45:00Z',
    contributors: 5,
    stars: 22,
    language: 'TypeScript',
    tags: ['mobile', 'react-native'],
    createdAt: '2025-09-10T00:00:00Z',
  },
  {
    id: 'proj-5',
    name: 'Vertex Data Pipeline',
    description:
      'ETL pipeline for processing user analytics events and generating aggregated insights.',
    repository: 'company/vertex-pipeline',
    branch: 'main',
    status: 'paused',
    deploymentStatus: 'pending',
    openPRs: 1,
    incidents: 0,
    healthScore: 72,
    lastDeployment: '2026-10-02T11:30:00Z',
    contributors: 4,
    stars: 15,
    language: 'Python',
    tags: ['data', 'etl'],
    createdAt: '2025-11-05T00:00:00Z',
  },
  {
    id: 'proj-6',
    name: 'Flux Documentation',
    description:
      'Developer documentation portal with interactive API references and onboarding guides.',
    repository: 'company/flux-docs',
    branch: 'main',
    status: 'archived',
    deploymentStatus: 'success',
    openPRs: 0,
    incidents: 0,
    healthScore: 90,
    lastDeployment: '2026-09-28T14:00:00Z',
    contributors: 3,
    stars: 12,
    language: 'MDX',
    tags: ['docs', 'internal'],
    createdAt: '2025-07-22T00:00:00Z',
  },
];

function makeCommits(count: number, author: string): Commit[] {
  const messages = [
    'feat: add real-time collaboration indicators',
    'fix: resolve race condition in websocket reconnection',
    'refactor: extract deployment status into shared hook',
    'chore: bump dependencies to latest patch versions',
    'test: add integration tests for PR review flow',
    'perf: memoize chart data transforms',
    'fix: correct aria labels on data table headers',
    'feat: implement command palette keyboard navigation',
    'refactor: consolidate error boundary patterns',
    'docs: update API documentation for v2 endpoints',
  ];
  return Array.from({ length: count }, (_, i) => ({
    id: `commit-${i}`,
    sha: Math.random().toString(16).substring(2, 9),
    message: messages[i % messages.length],
    author,
    authorAvatar: avatar(author),
    timestamp: new Date(
      Date.now() - (count - i) * 3600000
    ).toISOString(),
    additions: Math.floor(Math.random() * 200) + 10,
    deletions: Math.floor(Math.random() * 80),
  }));
}

function makeFileChanges(count: number): FileChange[] {
  const paths = [
    'src/components/Dashboard/MetricCard.tsx',
    'src/hooks/useDeploymentStatus.ts',
    'src/features/prs/PRReviewPanel.tsx',
    'src/lib/api/deployments.ts',
    'src/components/ui/DataTable.tsx',
    'src/stores/commandPalette.ts',
    'src/app/dashboard/page.tsx',
    'src/types/deployment.ts',
    'src/utils/riskAssessment.ts',
    'src/components/charts/PerformanceChart.tsx',
  ];
  const statuses: FileChange['status'][] = [
    'modified',
    'added',
    'modified',
    'modified',
    'added',
    'modified',
    'deleted',
    'modified',
    'added',
    'modified',
  ];
  const languages = [
    'TypeScript',
    'TypeScript',
    'TSX',
    'TypeScript',
    'TSX',
    'TypeScript',
    'TSX',
    'TypeScript',
    'TypeScript',
    'TSX',
  ];
  return Array.from({ length: count }, (_, i) => ({
    id: `file-${i}`,
    path: paths[i % paths.length],
    status: statuses[i % statuses.length],
    additions: Math.floor(Math.random() * 150) + 5,
    deletions: Math.floor(Math.random() * 50),
    language: languages[i % languages.length],
  }));
}

function makeChecks(): Check[] {
  return [
    {
      id: 'check-1',
      name: 'Unit Tests',
      status: 'success',
      duration: 42,
      type: 'test',
    },
    {
      id: 'check-2',
      name: 'E2E Tests',
      status: 'success',
      duration: 128,
      type: 'test',
    },
    {
      id: 'check-3',
      name: 'Lint',
      status: 'success',
      duration: 15,
      type: 'lint',
    },
    {
      id: 'check-4',
      name: 'Type Check',
      status: 'success',
      duration: 22,
      type: 'build',
    },
    {
      id: 'check-5',
      name: 'Build',
      status: 'success',
      duration: 68,
      type: 'build',
    },
    {
      id: 'check-6',
      name: 'Security Scan',
      status: 'failed',
      duration: 35,
      type: 'security',
    },
  ];
}

function makeComments(): Comment[] {
  return [
    {
      id: 'comment-1',
      author: 'Sarah Kim',
      authorAvatar: avatar('Sarah Kim'),
      body: 'The websocket reconnection logic looks solid. Have we considered adding an exponential backoff for production environments?',
      timestamp: new Date(Date.now() - 7200000).toISOString(),
      type: 'review',
    },
    {
      id: 'comment-2',
      author: 'Marcus Rivera',
      authorAvatar: avatar('Marcus Rivera'),
      body: 'Good catch on the race condition. The fix makes sense — we should probably add a test case for the concurrent disconnect scenario.',
      timestamp: new Date(Date.now() - 3600000).toISOString(),
      type: 'comment',
    },
    {
      id: 'comment-3',
      author: 'Priya Patel',
      authorAvatar: avatar('Priya Patel'),
      body: 'Approved. The memoization in the chart transforms is a nice performance win.',
      timestamp: new Date(Date.now() - 1800000).toISOString(),
      type: 'approval',
    },
  ];
}

export const pullRequests: PullRequest[] = [
  {
    id: 'pr-1',
    projectId: 'proj-1',
    number: 847,
    title: 'Add real-time collaboration indicators to dashboard widgets',
    description:
      'This PR introduces live presence indicators on dashboard widgets, showing when teammates are actively viewing or editing shared metrics. Uses WebSocket connections with automatic reconnection and graceful fallback to polling.',
    author: 'Marcus Rivera',
    authorAvatar: avatar('Marcus Rivera'),
    status: 'open',
    branch: 'feature/realtime-collab',
    baseBranch: 'main',
    filesChanged: 12,
    additions: 487,
    deletions: 93,
    testsPassed: 142,
    testsFailed: 0,
    testsTotal: 142,
    riskScore: 34,
    riskLevel: 'low',
    commits: makeCommits(5, 'Marcus Rivera'),
    fileChanges: makeFileChanges(12),
    checks: makeChecks(),
    comments: makeComments(),
    reviewStatus: 'approved',
    updatedAt: new Date(Date.now() - 1800000).toISOString(),
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    labels: ['enhancement', 'realtime'],
  },
  {
    id: 'pr-2',
    projectId: 'proj-1',
    number: 846,
    title: 'Refactor deployment status polling into shared hook with SSE fallback',
    description:
      'Extracts the deployment status polling logic from multiple components into a reusable `useDeploymentStatus` hook. Adds Server-Sent Events as a primary transport with polling fallback for environments where SSE is not available.',
    author: 'Priya Patel',
    authorAvatar: avatar('Priya Patel'),
    status: 'open',
    branch: 'refactor/deployment-hook',
    baseBranch: 'main',
    filesChanged: 8,
    additions: 234,
    deletions: 178,
    testsPassed: 98,
    testsFailed: 2,
    testsTotal: 100,
    riskScore: 58,
    riskLevel: 'medium',
    commits: makeCommits(3, 'Priya Patel'),
    fileChanges: makeFileChanges(8),
    checks: makeChecks(),
    comments: makeComments().slice(0, 2),
    reviewStatus: 'changes_requested',
    updatedAt: new Date(Date.now() - 3600000).toISOString(),
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    labels: ['refactor', 'tech-debt'],
  },
  {
    id: 'pr-3',
    projectId: 'proj-2',
    number: 312,
    title: 'Fix authentication bypass in rate limiting middleware under high load',
    description:
      'Under high concurrent load, the rate limiter was incorrectly bypassing authentication checks for requests that arrived within the same millisecond. This patches the race condition by adding a mutex around the auth verification step.',
    author: 'Sarah Kim',
    authorAvatar: avatar('Sarah Kim'),
    status: 'open',
    branch: 'fix/auth-bypass-rate-limit',
    baseBranch: 'main',
    filesChanged: 4,
    additions: 89,
    deletions: 23,
    testsPassed: 67,
    testsFailed: 0,
    testsTotal: 67,
    riskScore: 82,
    riskLevel: 'high',
    commits: makeCommits(2, 'Sarah Kim'),
    fileChanges: makeFileChanges(4),
    checks: makeChecks(),
    comments: makeComments().slice(1),
    reviewStatus: 'pending',
    updatedAt: new Date(Date.now() - 7200000).toISOString(),
    createdAt: new Date(Date.now() - 43200000).toISOString(),
    labels: ['security', 'critical', 'bugfix'],
  },
  {
    id: 'pr-4',
    projectId: 'proj-1',
    number: 845,
    title: 'Implement command palette with keyboard navigation and fuzzy search',
    description:
      'Adds a CMD/CTRL+K command palette with fuzzy search, keyboard navigation, and contextual actions. Supports navigation commands, theme toggling, and page-specific actions.',
    author: 'Jordan Lee',
    authorAvatar: avatar('Jordan Lee'),
    status: 'merged',
    branch: 'feature/command-palette',
    baseBranch: 'main',
    filesChanged: 15,
    additions: 612,
    deletions: 45,
    testsPassed: 156,
    testsFailed: 0,
    testsTotal: 156,
    riskScore: 22,
    riskLevel: 'low',
    commits: makeCommits(4, 'Jordan Lee'),
    fileChanges: makeFileChanges(15),
    checks: makeChecks(),
    comments: makeComments(),
    reviewStatus: 'approved',
    updatedAt: new Date(Date.now() - 259200000).toISOString(),
    createdAt: new Date(Date.now() - 345600000).toISOString(),
    labels: ['feature', 'ux'],
  },
  {
    id: 'pr-5',
    projectId: 'proj-3',
    number: 198,
    title: 'Add accessible color tokens and WCAG-compliant contrast ratios',
    description:
      'Updates the design system color tokens to meet WCAG 2.1 AA contrast ratios. Adds automated accessibility tests using axe-core.',
    author: 'Emma Wilson',
    authorAvatar: avatar('Emma Wilson'),
    status: 'open',
    branch: 'feature/a11y-tokens',
    baseBranch: 'main',
    filesChanged: 6,
    additions: 143,
    deletions: 87,
    testsPassed: 45,
    testsFailed: 0,
    testsTotal: 45,
    riskScore: 28,
    riskLevel: 'low',
    commits: makeCommits(2, 'Emma Wilson'),
    fileChanges: makeFileChanges(6),
    checks: makeChecks(),
    comments: [],
    reviewStatus: 'pending',
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
    createdAt: new Date(Date.now() - 129600000).toISOString(),
    labels: ['accessibility', 'design-system'],
  },
  {
    id: 'pr-6',
    projectId: 'proj-2',
    number: 311,
    title: 'Migrate from Redis pub/sub to Kafka for event distribution',
    description:
      'Replaces Redis pub/sub with Apache Kafka for internal event distribution. This change affects all services that consume events from the gateway.',
    author: 'Marcus Rivera',
    authorAvatar: avatar('Marcus Rivera'),
    status: 'draft',
    branch: 'feature/kafka-migration',
    baseBranch: 'main',
    filesChanged: 23,
    additions: 891,
    deletions: 412,
    testsPassed: 34,
    testsFailed: 12,
    testsTotal: 46,
    riskScore: 91,
    riskLevel: 'critical',
    commits: makeCommits(8, 'Marcus Rivera'),
    fileChanges: makeFileChanges(23),
    checks: makeChecks(),
    comments: [],
    reviewStatus: 'pending',
    updatedAt: new Date(Date.now() - 10800000).toISOString(),
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    labels: ['migration', 'infrastructure', 'wip'],
  },
  {
    id: 'pr-7',
    projectId: 'proj-4',
    number: 156,
    title: 'Add push notification preferences and quiet hours',
    description:
      'Implements user-configurable push notification preferences with quiet hours support. Notifications are suppressed during configured time windows.',
    author: 'Priya Patel',
    authorAvatar: avatar('Priya Patel'),
    status: 'open',
    branch: 'feature/notification-prefs',
    baseBranch: 'develop',
    filesChanged: 9,
    additions: 345,
    deletions: 67,
    testsPassed: 78,
    testsFailed: 0,
    testsTotal: 78,
    riskScore: 41,
    riskLevel: 'medium',
    commits: makeCommits(3, 'Priya Patel'),
    fileChanges: makeFileChanges(9),
    checks: makeChecks(),
    comments: makeComments().slice(0, 1),
    reviewStatus: 'reviewed',
    updatedAt: new Date(Date.now() - 14400000).toISOString(),
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    labels: ['feature', 'notifications'],
  },
  {
    id: 'pr-8',
    projectId: 'proj-1',
    number: 844,
    title: 'Optimize chart rendering with canvas-based virtualization',
    description:
      'Replaces SVG rendering for large datasets with a canvas-based approach that virtualizes off-screen points. Reduces render time by 60% for datasets over 1000 points.',
    author: 'Jordan Lee',
    authorAvatar: avatar('Jordan Lee'),
    status: 'closed',
    branch: 'perf/canvas-charts',
    baseBranch: 'main',
    filesChanged: 7,
    additions: 423,
    deletions: 198,
    testsPassed: 112,
    testsFailed: 0,
    testsTotal: 112,
    riskScore: 55,
    riskLevel: 'medium',
    commits: makeCommits(4, 'Jordan Lee'),
    fileChanges: makeFileChanges(7),
    checks: makeChecks(),
    comments: makeComments().slice(2),
    reviewStatus: 'reviewed',
    updatedAt: new Date(Date.now() - 432000000).toISOString(),
    createdAt: new Date(Date.now() - 518400000).toISOString(),
    labels: ['performance', 'charts'],
  },
];

function makeDeploymentLogs(env: string): DeploymentLogEntry[] {
  const baseLogs: { level: DeploymentLogEntry['level']; message: string }[] = [
    { level: 'info', message: `Starting deployment to ${env}` },
    { level: 'info', message: 'Building application bundle...' },
    { level: 'info', message: 'Installing dependencies (npm ci)' },
    { level: 'info', message: 'Running TypeScript compiler...' },
    { level: 'info', message: 'Type check passed' },
    { level: 'info', message: 'Running ESLint...' },
    { level: 'info', message: 'Lint check passed' },
    { level: 'info', message: 'Running unit tests...' },
    { level: 'info', message: '142 tests passed, 0 failed' },
    { level: 'info', message: 'Building production bundle...' },
    { level: 'info', message: 'Bundle size: 287 KB gzipped' },
    { level: 'info', message: 'Uploading to CDN...' },
    { level: 'info', message: 'Running database migrations...' },
    { level: 'info', message: '3 migrations applied successfully' },
    { level: 'info', message: 'Health check: /api/health -> 200 OK' },
    { level: 'info', message: 'Health check: /api/metrics -> 200 OK' },
    { level: 'info', message: 'Switching traffic to new deployment...' },
    { level: 'info', message: 'Deployment completed successfully' },
  ];
  const failedLogs = [
    { level: 'info', message: 'Running database migrations...' },
    { level: 'warn', message: 'Migration 004_add_index is taking longer than expected' },
    { level: 'error', message: 'Migration failed: connection timeout after 30000ms' },
    { level: 'error', message: 'Deployment failed during migration step' },
    { level: 'info', message: 'Rolling back to previous deployment...' },
    { level: 'info', message: 'Rollback complete' },
  ];
  return (baseLogs).map((log, i) => ({
    id: `log-${i}`,
    timestamp: new Date(Date.now() - (baseLogs.length - i) * 5000).toISOString(),
    level: log.level,
    message: log.message,
  }));
}

function makeDeploymentMetrics(): DeploymentMetric[] {
  return [
    {
      label: 'Response Time',
      value: 142,
      unit: 'ms',
      change: -12,
      previousValue: 154,
    },
    {
      label: 'Error Rate',
      value: 0.8,
      unit: '%',
      change: -0.3,
      previousValue: 1.1,
    },
    {
      label: 'Throughput',
      value: 2840,
      unit: 'req/s',
      change: 320,
      previousValue: 2520,
    },
    {
      label: 'CPU Usage',
      value: 38,
      unit: '%',
      change: 5,
      previousValue: 33,
    },
    {
      label: 'Memory Usage',
      value: 512,
      unit: 'MB',
      change: -24,
      previousValue: 536,
    },
    {
      label: 'Apdex Score',
      value: 0.94,
      unit: '',
      change: 0.03,
      previousValue: 0.91,
    },
  ];
}

export const deployments: Deployment[] = [
  {
    id: 'deploy-1',
    projectId: 'proj-1',
    status: 'success',
    environment: 'production',
    commitSha: 'a3f7d92',
    commitMessage: 'feat: add real-time collaboration indicators',
    branch: 'main',
    author: 'Marcus Rivera',
    authorAvatar: avatar('Marcus Rivera'),
    duration: 287,
    startTime: '2026-10-05T08:25:00Z',
    endTime: '2026-10-05T08:30:00Z',
    url: 'https://atlas.company.com',
    logs: makeDeploymentLogs('production'),
    metrics: makeDeploymentMetrics(),
    testsPassed: 142,
    testsTotal: 142,
  },
  {
    id: 'deploy-2',
    projectId: 'proj-2',
    status: 'failed',
    environment: 'production',
    commitSha: 'b8e2c41',
    commitMessage: 'fix: authentication bypass in rate limiting middleware',
    branch: 'main',
    author: 'Sarah Kim',
    authorAvatar: avatar('Sarah Kim'),
    duration: 156,
    startTime: '2026-10-05T07:12:00Z',
    endTime: '2026-10-05T07:15:00Z',
    url: 'https://api.company.com',
    logs: [
      ...makeDeploymentLogs('production').slice(0, 13),
      ...makeDeploymentLogs('production').slice(-2).map((l, i) => ({
        ...l,
        id: `log-fail-${i}`,
        level: 'error' as const,
        message: i === 0 ? 'Migration failed: connection timeout after 30000ms' : 'Deployment failed during migration step',
      })),
    ],
    metrics: makeDeploymentMetrics().map((m) => ({
      ...m,
      change: m.label === 'Error Rate' ? 2.1 : m.change,
      value: m.label === 'Error Rate' ? 3.2 : m.value,
    })),
    testsPassed: 65,
    testsTotal: 67,
  },
  {
    id: 'deploy-3',
    projectId: 'proj-3',
    status: 'success',
    environment: 'production',
    commitSha: 'c4d9a77',
    commitMessage: 'feat: add accessible color tokens',
    branch: 'main',
    author: 'Emma Wilson',
    authorAvatar: avatar('Emma Wilson'),
    duration: 198,
    startTime: '2026-10-04T15:57:00Z',
    endTime: '2026-10-04T16:00:00Z',
    url: 'https://design.company.com',
    logs: makeDeploymentLogs('production'),
    metrics: makeDeploymentMetrics(),
    testsPassed: 45,
    testsTotal: 45,
  },
  {
    id: 'deploy-4',
    projectId: 'proj-4',
    status: 'in_progress',
    environment: 'staging',
    commitSha: 'd1f5e83',
    commitMessage: 'feat: add push notification preferences',
    branch: 'develop',
    author: 'Priya Patel',
    authorAvatar: avatar('Priya Patel'),
    duration: 0,
    startTime: '2026-10-05T09:45:00Z',
    endTime: null,
    url: 'https://staging.pulse.company.com',
    logs: makeDeploymentLogs('staging').slice(0, 8),
    metrics: [],
    testsPassed: 0,
    testsTotal: 78,
  },
  {
    id: 'deploy-5',
    projectId: 'proj-1',
    status: 'success',
    environment: 'staging',
    commitSha: 'e7a3b29',
    commitMessage: 'refactor: deployment status shared hook',
    branch: 'refactor/deployment-hook',
    author: 'Priya Patel',
    authorAvatar: avatar('Priya Patel'),
    duration: 224,
    startTime: '2026-10-04T22:10:00Z',
    endTime: '2026-10-04T22:14:00Z',
    url: 'https://staging.atlas.company.com',
    logs: makeDeploymentLogs('staging'),
    metrics: makeDeploymentMetrics(),
    testsPassed: 100,
    testsTotal: 100,
  },
  {
    id: 'deploy-6',
    projectId: 'proj-2',
    status: 'success',
    environment: 'staging',
    commitSha: 'f2c8d64',
    commitMessage: 'chore: bump dependencies',
    branch: 'main',
    author: 'Marcus Rivera',
    authorAvatar: avatar('Marcus Rivera'),
    duration: 167,
    startTime: '2026-10-03T14:20:00Z',
    endTime: '2026-10-03T14:23:00Z',
    url: 'https://staging.api.company.com',
    logs: makeDeploymentLogs('staging'),
    metrics: makeDeploymentMetrics(),
    testsPassed: 67,
    testsTotal: 67,
  },
  {
    id: 'deploy-7',
    projectId: 'proj-1',
    status: 'cancelled',
    environment: 'preview',
    commitSha: 'a9b4f17',
    commitMessage: 'experiment: canvas-based chart rendering',
    branch: 'perf/canvas-charts',
    author: 'Jordan Lee',
    authorAvatar: avatar('Jordan Lee'),
    duration: 45,
    startTime: '2026-10-03T10:00:00Z',
    endTime: '2026-10-03T10:01:00Z',
    url: '',
    logs: makeDeploymentLogs('preview').slice(0, 3),
    metrics: [],
    testsPassed: 0,
    testsTotal: 112,
  },
  {
    id: 'deploy-8',
    projectId: 'proj-3',
    status: 'success',
    environment: 'preview',
    commitSha: 'b5e2d88',
    commitMessage: 'docs: update component documentation',
    branch: 'main',
    author: 'Emma Wilson',
    authorAvatar: avatar('Emma Wilson'),
    duration: 89,
    startTime: '2026-10-02T09:30:00Z',
    endTime: '2026-10-02T09:32:00Z',
    url: 'https://preview.design.company.com',
    logs: makeDeploymentLogs('preview'),
    metrics: makeDeploymentMetrics(),
    testsPassed: 45,
    testsTotal: 45,
  },
];

function makeIncidentTimeline(
  incidentId: string,
  isResolved: boolean
): IncidentTimelineEvent[] {
  const events: IncidentTimelineEvent[] = [
    {
      id: `${incidentId}-t1`,
      type: 'deployment',
      title: 'Deployment #2 to production',
      description: 'Orion API Gateway deployed commit b8e2c41 to production',
      timestamp: '2026-10-05T07:15:00Z',
    },
    {
      id: `${incidentId}-t2`,
      type: 'error',
      title: 'Error rate spike detected',
      description: 'Error rate increased from 0.8% to 3.2% within 2 minutes of deployment',
      timestamp: '2026-10-05T07:17:00Z',
    },
    {
      id: `${incidentId}-t3`,
      type: 'latency',
      title: 'Latency increase observed',
      description: 'P95 latency increased from 142ms to 890ms on /api/auth endpoints',
      timestamp: '2026-10-05T07:18:00Z',
    },
    {
      id: `${incidentId}-t4`,
      type: 'created',
      title: 'Incident created',
      description: 'Auto-detected by monitoring system. Severity set to High.',
      timestamp: '2026-10-05T07:20:00Z',
      author: 'Monitoring System',
      authorAvatar: avatar('Monitoring'),
    },
    {
      id: `${incidentId}-t5`,
      type: 'investigation',
      title: 'Investigation started',
      description: 'Sarah Kim assigned as incident commander. Initial investigation points to database migration timeout.',
      timestamp: '2026-10-05T07:25:00Z',
      author: 'Sarah Kim',
      authorAvatar: avatar('Sarah Kim'),
    },
    {
      id: `${incidentId}-t6`,
      type: 'comment',
      title: 'Marcus Rivera joined investigation',
      description: 'Checking if the migration timeout is related to the connection pool changes in the recent PR.',
      timestamp: '2026-10-05T07:32:00Z',
      author: 'Marcus Rivera',
      authorAvatar: avatar('Marcus Rivera'),
    },
  ];

  if (isResolved) {
    events.push(
      {
        id: `${incidentId}-t7`,
        type: 'mitigation',
        title: 'Mitigation applied',
        description: 'Rolled back deployment to previous version. Error rate dropping.',
        timestamp: '2026-10-05T07:45:00Z',
        author: 'Sarah Kim',
        authorAvatar: avatar('Sarah Kim'),
      },
      {
        id: `${incidentId}-t8`,
        type: 'resolution',
        title: 'Incident resolved',
        description: 'Error rate back to normal. Latency within acceptable range. Monitoring for 30 minutes.',
        timestamp: '2026-10-05T08:15:00Z',
        author: 'Sarah Kim',
        authorAvatar: avatar('Sarah Kim'),
      }
    );
  }

  return events;
}

export const incidents: Incident[] = [
  {
    id: 'inc-1',
    projectId: 'proj-2',
    title: 'Authentication timeout for API Gateway users',
    description:
      'Users experiencing intermittent authentication timeouts after the latest production deployment. Error rate spiked to 3.2% and P95 latency increased to 890ms on auth endpoints.',
    severity: 'high',
    status: 'investigating',
    service: 'auth-service',
    assignee: 'Sarah Kim',
    assigneeAvatar: avatar('Sarah Kim'),
    createdAt: '2026-10-05T07:20:00Z',
    resolvedAt: null,
    affectedUsers: 1240,
    duration: 165,
    timeline: makeIncidentTimeline('inc-1', false),
    tags: ['auth', 'production', 'database'],
  },
  {
    id: 'inc-2',
    projectId: 'proj-2',
    title: 'Database connection pool exhaustion',
    description:
      'Connection pool exhausted during peak traffic, causing cascading failures across multiple services. Root cause identified as a missing connection timeout configuration.',
    severity: 'critical',
    status: 'identified',
    service: 'database',
    assignee: 'Marcus Rivera',
    assigneeAvatar: avatar('Marcus Rivera'),
    createdAt: '2026-10-05T06:45:00Z',
    resolvedAt: null,
    affectedUsers: 3400,
    duration: 240,
    timeline: makeIncidentTimeline('inc-2', false),
    tags: ['database', 'production', 'connection-pool'],
  },
  {
    id: 'inc-3',
    projectId: 'proj-1',
    title: 'Dashboard widgets not loading for some users',
    description:
      'A subset of users reporting blank dashboard widgets after the real-time collaboration feature deployment. Issue appears to be related to WebSocket connections in restricted network environments.',
    severity: 'medium',
    status: 'monitoring',
    service: 'websocket-gateway',
    assignee: 'Marcus Rivera',
    assigneeAvatar: avatar('Marcus Rivera'),
    createdAt: '2026-10-05T08:35:00Z',
    resolvedAt: null,
    affectedUsers: 87,
    duration: 90,
    timeline: makeIncidentTimeline('inc-3', false),
    tags: ['websocket', 'frontend', 'regression'],
  },
  {
    id: 'inc-4',
    projectId: 'proj-1',
    title: 'Slow chart rendering on large datasets',
    description:
      'Performance degradation when rendering charts with datasets exceeding 1000 data points. Identified as an SVG rendering bottleneck.',
    severity: 'low',
    status: 'resolved',
    service: 'chart-renderer',
    assignee: 'Jordan Lee',
    assigneeAvatar: avatar('Jordan Lee'),
    createdAt: '2026-10-03T14:00:00Z',
    resolvedAt: '2026-10-03T18:30:00Z',
    affectedUsers: 23,
    duration: 270,
    timeline: makeIncidentTimeline('inc-4', true),
    tags: ['performance', 'charts'],
  },
  {
    id: 'inc-5',
    projectId: 'proj-2',
    title: 'Rate limiter incorrectly blocking legitimate traffic',
    description:
      'Rate limiting middleware was too aggressive after a configuration change, blocking legitimate API requests from high-volume clients.',
    severity: 'medium',
    status: 'resolved',
    service: 'rate-limiter',
    assignee: 'Sarah Kim',
    assigneeAvatar: avatar('Sarah Kim'),
    createdAt: '2026-10-02T10:00:00Z',
    resolvedAt: '2026-10-02T12:30:00Z',
    affectedUsers: 450,
    duration: 150,
    timeline: makeIncidentTimeline('inc-5', true),
    tags: ['rate-limiting', 'configuration'],
  },
];

export const dashboardMetrics: DashboardMetrics = {
  activeProjects: 4,
  openPRs: 7,
  recentDeployments: 12,
  activeIncidents: 3,
  deploymentSuccessRate: 87.5,
  errorRate: 1.2,
  engineeringHealth: 82,
  trends: {
    activeProjects: 1,
    openPRs: -2,
    recentDeployments: 4,
    activeIncidents: 2,
    deploymentSuccessRate: -2.5,
    errorRate: 0.4,
    engineeringHealth: -3,
  },
};

export const deploymentChartData: DeploymentChartDataPoint[] = Array.from(
  { length: 14 },
  (_, i) => {
    const date = new Date(Date.now() - (13 - i) * 86400000);
    const total = Math.floor(Math.random() * 6) + 3;
    const failed = Math.floor(Math.random() * 2);
    return {
      date: date.toISOString().split('T')[0],
      success: total - failed,
      failed,
      total,
    };
  }
);

export const performanceChartData: PerformanceChartDataPoint[] = Array.from(
  { length: 14 },
  (_, i) => {
    const date = new Date(Date.now() - (13 - i) * 86400000);
    return {
      date: date.toISOString().split('T')[0],
      responseTime: Math.floor(Math.random() * 80) + 120,
      errorRate: Math.random() * 1.5 + 0.3,
      throughput: Math.floor(Math.random() * 600) + 2200,
    };
  }
);

export const activityFeed: ActivityFeedItem[] = [
  {
    id: 'act-1',
    type: 'deployment',
    title: 'Deployment to production',
    description: 'Atlas Web Platform deployed successfully to production',
    actor: 'Marcus Rivera',
    actorAvatar: avatar('Marcus Rivera'),
    timestamp: new Date(Date.now() - 1800000).toISOString(),
    projectId: 'proj-1',
    projectName: 'Atlas Web Platform',
  },
  {
    id: 'act-2',
    type: 'incident',
    title: 'Incident created',
    description: 'Authentication timeout for API Gateway users',
    actor: 'Monitoring System',
    actorAvatar: avatar('Monitoring'),
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    projectId: 'proj-2',
    projectName: 'Orion API Gateway',
  },
  {
    id: 'act-3',
    type: 'pr',
    title: 'Pull request opened',
    description: '#847 Add real-time collaboration indicators to dashboard widgets',
    actor: 'Marcus Rivera',
    actorAvatar: avatar('Marcus Rivera'),
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    projectId: 'proj-1',
    projectName: 'Atlas Web Platform',
  },
  {
    id: 'act-4',
    type: 'pr',
    title: 'Pull request approved',
    description: '#845 Implement command palette with keyboard navigation',
    actor: 'Priya Patel',
    actorAvatar: avatar('Priya Patel'),
    timestamp: new Date(Date.now() - 10800000).toISOString(),
    projectId: 'proj-1',
    projectName: 'Atlas Web Platform',
  },
  {
    id: 'act-5',
    type: 'deployment',
    title: 'Deployment failed',
    description: 'Orion API Gateway deployment failed during migration step',
    actor: 'Sarah Kim',
    actorAvatar: avatar('Sarah Kim'),
    timestamp: new Date(Date.now() - 14400000).toISOString(),
    projectId: 'proj-2',
    projectName: 'Orion API Gateway',
  },
  {
    id: 'act-6',
    type: 'incident',
    title: 'Incident severity increased',
    description: 'Database connection pool exhaustion elevated to critical',
    actor: 'Marcus Rivera',
    actorAvatar: avatar('Marcus Rivera'),
    timestamp: new Date(Date.now() - 18000000).toISOString(),
    projectId: 'proj-2',
    projectName: 'Orion API Gateway',
  },
  {
    id: 'act-7',
    type: 'pr',
    title: 'Pull request merged',
    description: '#844 Optimize chart rendering with canvas-based virtualization',
    actor: 'Jordan Lee',
    actorAvatar: avatar('Jordan Lee'),
    timestamp: new Date(Date.now() - 21600000).toISOString(),
    projectId: 'proj-1',
    projectName: 'Atlas Web Platform',
  },
  {
    id: 'act-8',
    type: 'team',
    title: 'Team member invited',
    description: 'Emma Wilson joined the team',
    actor: 'Alex Chen',
    actorAvatar: avatar('Alex Chen'),
    timestamp: new Date(Date.now() - 86400000).toISOString(),
  },
];
